### ISSUE TITLE
Time scedule!

### ISSUE THREAD

**Issue by Chomikmarkus** [redlure/redlure-server#14]
Hey when trying to schedule campaign it throws error and does not start campaign!
![Screenshot_20220613-014126_JuiceSSH](https://user-images.githubusercontent.com/92059377/173256490-7b3d7953-f0f8-4b9e-b19c-8cc5355e0067.jpg)

**Comment by Tw1sm** [comment]
What value did you enter into the *Start Time* input field? The fields could likely use some better client/server side input validation, but the input is expected to be in the format of: `MM/DD/YYYY HH:MM:SS`.  Based on the error you're getting, without more information, I'd assume the value you submitted was either missing a space between the date and time, or incomplete.
